- name: Optimize ulimit
  pam_limits: 
    domain: "*"
    limit_type: "{{ item[0] }}"
    limit_item: "{{ item[1] }}"
    value: 65535
  with_nested:
    - ['soft','hard']
    - ['nproc','nofile']

- name: optimize kernel parameter
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: 'vm.swappiness', value: '1' }
    - { name: 'vm.dirty_ratio', value: '20' }
    - { name: 'vm.dirty_background_ratio', value: '30' }

- name: untar mysql.tar.gz
  unarchive: src={{ source_dir }}/{{ mysql_package_name }}.tar.gz dest={{ mysql_basedir }}/ remote_src=yes
  tags: 
    - tar

- name: soft link mysql package
  file: src={{ mysql_basedir }}/{{ mysql_package_name }} path={{ mysql_basedir }}/mysql owner=mysql group=mysql state=link

- name: install mysql with shell script
  shell: /usr/bin/sh {{ source_dir }}/mysql_install.sh
  register: result


- name: Update initial root password
  shell: /usr/bin/sh {{ source_dir }}/update_initial_root_password.sh
  when: result|success
  notify: 
   - delete the update password script
