- name: Optimize ulimit
  pam_limits: 
    domain: "*"
    limit_type: "{{ item[0] }}"
    limit_item: "{{ item[1] }}"
    value: 65535
  # backup: yes
  with_nested:
    - ['soft','hard']
    - ['nproc','nofile']

- name: optimize kernel parameter
  sysctl: 
    name: "{{ item.name }}"
    value: "{{ item.value }}"
    state: present
    reload: yes
  with_items:
    - { name: 'vm.swappiness', value: '1' }
    - { name: 'vm.dirty_ratio', value: '20' }
    - { name: 'vm.dirty_background_ratio', value: '30' }

- name: Ensure selinux is closed
  selinux:
    state: disabled
  notify:
    - Reboot OS system

- name: create mysql user
  user: name=mysql

- name: create mysql datadir
  file: path={{ mysql_datadir }} owner=mysql group=mysql state=directory

- name: copy my.cnf to client
  template: src=my.cnf.j2 dest=/etc/my.cnf owner=root group=root backup=yes

- name: copy update mysql root password script to client
  template: src=update_initial_root_password.sh.j2 dest={{ source_dir }}/update_initial_root_password.sh owner=root group=root

- name: copy mysql source code to client
  copy: src={{ mysql_package_name }}.tar.gz dest={{ source_dir }} owner=root group=root
  tags:
    - tar

- name: copy mysql install script to client
  template: src=mysql_install.sh.j2 dest={{ source_dir }}/mysql_install.sh owner=root group=root mode=0755

