- name: Ensure mysql backup dir exists
  file: path={{ mysql_backupdir_prefix }} owner=mysql group=mysql state=directory

- name: Ensure MySQL-python package is ready
  yum: name=MySQL-python state=present
  tags:
   - python

- name: Copy xtrabackup to client
  copy: 
    src: percona-xtrabackup-24-2.4.12-1.el7.x86_64.rpm
    dest: "{{ source_dir }}"
    owner: root
    group: root
  register: result
  tags: 
    - tar

- name: Yum localinstall xtrabackup 
  yum: 
    name: "{{ source_dir }}/percona-xtrabackup-24-2.4.12-1.el7.x86_64.rpm"
    state: present
  when: result|success
  
- name: Ensure mysql backup user exists
  mysql_user: 
    login_user: "{{ mysql_login_user.name }}"
    login_password: "{{ mysql_login_user.password }}"
    login_unix_socket: "{{ mysql_login_user.unix_socket }}"
    name: "{{ mysql_backup_user.name }}" 
    password: "{{ mysql_backup_user.password }}"
    host: "{{ mysql_backup_user.host }}"
    priv: "{{ mysql_backup_user.priv | default('*.*:RELOAD, LOCK TABLES, PROCESS, REPLICATION CLIENT') }}"
    state: present
  when:
    (mysql_is_replication == 'yes' and mysql_replication_role == 'master')
    or (mysql_is_replication == 'no')
  tags:
    - bakuser
